### ISSUE TITLE
custom_id problems

### ISSUE THREAD

**Issue by fradav** [kinjo/org-impress-js.el#12]
Currently, `custom_id` property doesn't work, it crashes in `org-impress-js-headline` function, because `extra-ids` got "link-solidified" two times. I could remove the second `mapconcat` doing this, so it doesn't crash any more. Now it doesn't work as expected, in the toc the `href` is set to the specified `custom_id`, it's good but not in the generated link in actual slide where we see something like `outline-container-<custom_id>`.
I think it would be nice if we could properly set this property to actually have something more significant url-tag names than `outline-container-unnumbered-3`.

**Comment by kinjo** [comment]
@fradav Oh, i'll take a look at this issue today.

**Comment by kinjo** [comment]
@fradav I just fixed it and tested it on README.org included in this repository. So it seems working well. How's that?

**Comment by fradav** [comment]
It's perfect! Thanks you very much!

As a side note, do you think it's a good idea to fork your repo to port it for jmpress.js ?

**Comment by kinjo** [comment]
It's wonderful idea! I'd like to try that! But unfortunately I have no enough time:-(
So why don't you try that? It's good reason to encourage you to start your new fasnating GitHub project.

**Comment by fradav** [comment]
I still have some doubts about the usefulness of such a port: the fact jmpress uses jQuery from scratch makes it very easy to add simple jQuery directives on a top of the bare html org-mode back-end exporter, like just adding the "step" and "slide" class to the back-end exported class and so on.  What do you think about this ?

**Comment by kinjo** [comment]
Does that mean the HTML generated from an Org file by original ox-html should be converted proper ones for jmpress with jQuery? If so, it sounds good!
But probably it will needs a new jQuery program to convert that. And also I think such an exporter no longer be needed to generate HTML but instead it may generate other data such as JSON convenient for jQuery.

**Comment by fradav** [comment]
Actually it's pretty simple, look at my [example](https://gist.github.com/3bbc45de959c98f36358.git)
It's not even using features from jmpress like templates and son on.

**Comment by kinjo** [comment]
@fradav Sorry for the late reply. I have took a look at your example. It's pretty great!
But I wonder that how do you do positioning, rotating and scaling for each specific slides?
In order to do that, ox-impress-js.el is providing special properties such as `data-x`,  `data-rotate-z`, `data-scale` and so on.
Do you have other nicer idea to do it without changing ox-html.el?

**Comment by fradav** [comment]
It's all done in jQuery/jmpress see [there](https://github.com/fradav/org-jmpress-js.el).
